### ISSUE TITLE
LICENCE?

### ISSUE THREAD

**Issue by zitterbewegung** [MichaelBurge/pyramid-scheme#1]
What licence is this under? (Apache 2.0 or MIT)

**Comment by zigguratt** [comment]
Either works for me. I'm very interested in this project.

**Comment by MichaelBurge** [comment]
Thanks for trying it out. I think MIT is good for this. I've pushed a LICENSE file with a copy of the MIT license to the repository.

It's a bit wild-west at the moment. The "run-tests.rkt" is the entry point I was using to get deployable bytecode. My workflow was:

1. Pick an example program like prog-factorial
2. Run "(full-debug-output prog-factorial)" in "run-tests.rkt" to get a bytecode listing
3. Use the "testrpc" tool to start a test EthereumJS instance
4. Paste the hexadecimal string from step 2 into "deploy.js", along with a wallet from step 3.
5. Paste the contents of "deploy.js" into a Javascript prompt attached to the Ethereum instance in step 3.

One missing feature is that the "(set! x 10)" built-in doesn't have an EVM code generator for its abstract machine operation. I was planning to implement that before the next article before anyone noticed. If you wanted to try your hand at it, "cg-op-define-variable!" in codegen.rkt would be a good template.

**Comment by MichaelBurge** [comment]
@zigguratt @zitterbewegung I set up a public Discord channel for the project that you may want to join: https://discord.gg/854RH6x
